# socket_shim_surface_test.rb
#
# Portable surface test: run with both CRuby and Spinel and compare stdout.

require_relative "../source/socket_shim"

def check(label, value)
  if value
    puts label + ":ok"
  else
    puts label + ":bad"
  end
end

check("class BasicSocket", defined?(BasicSocket) == "constant")
check("class IPSocket", defined?(IPSocket) == "constant")
check("class TCPSocket", defined?(TCPSocket) == "constant")
check("class TCPServer", defined?(TCPServer) == "constant")
check("class UDPSocket", defined?(UDPSocket) == "constant")
check("class UNIXSocket", defined?(UNIXSocket) == "constant")
check("class UNIXServer", defined?(UNIXServer) == "constant")
check("class Socket", defined?(Socket) == "constant")
check("class Addrinfo", defined?(Addrinfo) == "constant")
check("class SocketError", defined?(SocketError) == "constant")
check("module Socket::Constants", Socket::Constants == Socket::Constants)
check("class Socket::Option", Socket::Option == Socket::Option)
check("class Socket::AncillaryData", Socket::AncillaryData == Socket::AncillaryData)
check("class Socket::Ifaddr", Socket::Ifaddr == Socket::Ifaddr)
check("class Socket::WaitReadable", Socket::WaitReadable == Socket::WaitReadable)
check("class Socket::WaitWritable", Socket::WaitWritable == Socket::WaitWritable)
check("class Socket::EAGAINWaitReadable", Socket::EAGAINWaitReadable == Socket::EAGAINWaitReadable)
check("class Socket::EAGAINWaitWritable", Socket::EAGAINWaitWritable == Socket::EAGAINWaitWritable)
check("class Socket::EWOULDBLOCKWaitReadable", Socket::EWOULDBLOCKWaitReadable == Socket::EWOULDBLOCKWaitReadable)
check("class Socket::EWOULDBLOCKWaitWritable", Socket::EWOULDBLOCKWaitWritable == Socket::EWOULDBLOCKWaitWritable)
check("class Socket::EINPROGRESSWaitReadable", Socket::EINPROGRESSWaitReadable == Socket::EINPROGRESSWaitReadable)
check("class Socket::EINPROGRESSWaitWritable", Socket::EINPROGRESSWaitWritable == Socket::EINPROGRESSWaitWritable)

check("BasicSocket.for_fd", BasicSocket.respond_to?(:for_fd))
check("BasicSocket.do_not_reverse_lookup", BasicSocket.respond_to?(:do_not_reverse_lookup))
check("BasicSocket.do_not_reverse_lookup=", BasicSocket.respond_to?(:do_not_reverse_lookup=))
check("IPSocket.getaddress", IPSocket.respond_to?(:getaddress))
check("TCPSocket.gethostbyname", TCPSocket.respond_to?(:gethostbyname))
check("TCPServer.open", TCPServer.respond_to?(:open))
check("UNIXSocket.pair", UNIXSocket.respond_to?(:pair))
check("UNIXSocket.socketpair", UNIXSocket.respond_to?(:socketpair))

check("Addrinfo.foreach", Addrinfo.respond_to?(:foreach))
check("Addrinfo.getaddrinfo", Addrinfo.respond_to?(:getaddrinfo))
check("Addrinfo.ip", Addrinfo.respond_to?(:ip))
check("Addrinfo.tcp", Addrinfo.respond_to?(:tcp))
check("Addrinfo.udp", Addrinfo.respond_to?(:udp))
check("Addrinfo.unix", Addrinfo.respond_to?(:unix))

check("Socket::Option.bool", Socket::Option.respond_to?(:bool))
check("Socket::Option.byte", Socket::Option.respond_to?(:byte))
check("Socket::Option.int", Socket::Option.respond_to?(:int))
check("Socket::Option.ipv4_multicast_loop", Socket::Option.respond_to?(:ipv4_multicast_loop))
check("Socket::Option.ipv4_multicast_ttl", Socket::Option.respond_to?(:ipv4_multicast_ttl))
check("Socket::Option.linger", Socket::Option.respond_to?(:linger))

check("Socket::AncillaryData.int", Socket::AncillaryData.respond_to?(:int))
check("Socket::AncillaryData.ip_pktinfo", Socket::AncillaryData.respond_to?(:ip_pktinfo))
check("Socket::AncillaryData.ipv6_pktinfo", Socket::AncillaryData.respond_to?(:ipv6_pktinfo))
check("Socket::AncillaryData.unix_rights", Socket::AncillaryData.respond_to?(:unix_rights))

check("Socket.accept_loop", Socket.respond_to?(:accept_loop))
check("Socket.getaddrinfo", Socket.respond_to?(:getaddrinfo))
check("Socket.gethostbyaddr", Socket.respond_to?(:gethostbyaddr))
check("Socket.gethostbyname", Socket.respond_to?(:gethostbyname))
check("Socket.gethostname", Socket.respond_to?(:gethostname))
check("Socket.getifaddrs", Socket.respond_to?(:getifaddrs))
check("Socket.getnameinfo", Socket.respond_to?(:getnameinfo))
check("Socket.getservbyname", Socket.respond_to?(:getservbyname))
check("Socket.getservbyport", Socket.respond_to?(:getservbyport))
check("Socket.ip_address_list", Socket.respond_to?(:ip_address_list))
check("Socket.pack_sockaddr_in", Socket.respond_to?(:pack_sockaddr_in))
check("Socket.pack_sockaddr_un", Socket.respond_to?(:pack_sockaddr_un))
check("Socket.pair", Socket.respond_to?(:pair))
check("Socket.sockaddr_in", Socket.respond_to?(:sockaddr_in))
check("Socket.sockaddr_un", Socket.respond_to?(:sockaddr_un))
check("Socket.socketpair", Socket.respond_to?(:socketpair))
check("Socket.tcp", Socket.respond_to?(:tcp))
check("Socket.tcp_server_loop", Socket.respond_to?(:tcp_server_loop))
check("Socket.tcp_server_sockets", Socket.respond_to?(:tcp_server_sockets))
check("Socket.udp_server_loop", Socket.respond_to?(:udp_server_loop))
check("Socket.udp_server_loop_on", Socket.respond_to?(:udp_server_loop_on))
check("Socket.udp_server_recv", Socket.respond_to?(:udp_server_recv))
check("Socket.udp_server_sockets", Socket.respond_to?(:udp_server_sockets))
check("Socket.unix", Socket.respond_to?(:unix))
check("Socket.unix_server_loop", Socket.respond_to?(:unix_server_loop))
check("Socket.unix_server_socket", Socket.respond_to?(:unix_server_socket))
check("Socket.unpack_sockaddr_in", Socket.respond_to?(:unpack_sockaddr_in))
check("Socket.unpack_sockaddr_un", Socket.respond_to?(:unpack_sockaddr_un))

basic_socket = BasicSocket.allocate
check("BasicSocket#close", basic_socket.respond_to?(:close))
check("BasicSocket#close_read", basic_socket.respond_to?(:close_read))
check("BasicSocket#close_write", basic_socket.respond_to?(:close_write))
check("BasicSocket#closed?", basic_socket.respond_to?(:closed?))
check("BasicSocket#connect_address", basic_socket.respond_to?(:connect_address))
check("BasicSocket#do_not_reverse_lookup", basic_socket.respond_to?(:do_not_reverse_lookup))
check("BasicSocket#do_not_reverse_lookup=", basic_socket.respond_to?(:do_not_reverse_lookup=))
check("BasicSocket#getpeereid", basic_socket.respond_to?(:getpeereid))
check("BasicSocket#getpeername", basic_socket.respond_to?(:getpeername))
check("BasicSocket#getsockname", basic_socket.respond_to?(:getsockname))
check("BasicSocket#getsockopt", basic_socket.respond_to?(:getsockopt))
check("BasicSocket#local_address", basic_socket.respond_to?(:local_address))
check("BasicSocket#readpartial", basic_socket.respond_to?(:readpartial))
check("BasicSocket#recv", basic_socket.respond_to?(:recv))
check("BasicSocket#recv_nonblock", basic_socket.respond_to?(:recv_nonblock))
check("BasicSocket#recvmsg", basic_socket.respond_to?(:recvmsg))
check("BasicSocket#recvmsg_nonblock", basic_socket.respond_to?(:recvmsg_nonblock))
check("BasicSocket#remote_address", basic_socket.respond_to?(:remote_address))
check("BasicSocket#send", basic_socket.respond_to?(:send))
check("BasicSocket#sendmsg", basic_socket.respond_to?(:sendmsg))
check("BasicSocket#sendmsg_nonblock", basic_socket.respond_to?(:sendmsg_nonblock))
check("BasicSocket#setsockopt", basic_socket.respond_to?(:setsockopt))
check("BasicSocket#shutdown", basic_socket.respond_to?(:shutdown))
check("BasicSocket#write", basic_socket.respond_to?(:write))

ip_socket = IPSocket.allocate
check("IPSocket#addr", ip_socket.respond_to?(:addr))
check("IPSocket#inspect", ip_socket.respond_to?(:inspect))
check("IPSocket#peeraddr", ip_socket.respond_to?(:peeraddr))
check("IPSocket#recvfrom", ip_socket.respond_to?(:recvfrom))

tcp_server = TCPServer.allocate
check("TCPServer#accept", tcp_server.respond_to?(:accept))
check("TCPServer#accept_nonblock", tcp_server.respond_to?(:accept_nonblock))
check("TCPServer#listen", tcp_server.respond_to?(:listen))
check("TCPServer#sysaccept", tcp_server.respond_to?(:sysaccept))

udp_socket = UDPSocket.allocate
check("UDPSocket#bind", udp_socket.respond_to?(:bind))
check("UDPSocket#connect", udp_socket.respond_to?(:connect))
check("UDPSocket#recvfrom_nonblock", udp_socket.respond_to?(:recvfrom_nonblock))
check("UDPSocket#send", udp_socket.respond_to?(:send))

unix_socket = UNIXSocket.allocate
check("UNIXSocket#addr", unix_socket.respond_to?(:addr))
check("UNIXSocket#path", unix_socket.respond_to?(:path))
check("UNIXSocket#peeraddr", unix_socket.respond_to?(:peeraddr))
check("UNIXSocket#recv_io", unix_socket.respond_to?(:recv_io))
check("UNIXSocket#recvfrom", unix_socket.respond_to?(:recvfrom))
check("UNIXSocket#send_io", unix_socket.respond_to?(:send_io))

unix_server = UNIXServer.allocate
check("UNIXServer#accept", unix_server.respond_to?(:accept))
check("UNIXServer#accept_nonblock", unix_server.respond_to?(:accept_nonblock))
check("UNIXServer#listen", unix_server.respond_to?(:listen))
check("UNIXServer#sysaccept", unix_server.respond_to?(:sysaccept))

raw_socket = Socket.allocate
check("Socket#accept", raw_socket.respond_to?(:accept))
check("Socket#accept_nonblock", raw_socket.respond_to?(:accept_nonblock))
check("Socket#bind", raw_socket.respond_to?(:bind))
check("Socket#connect", raw_socket.respond_to?(:connect))
check("Socket#connect_nonblock", raw_socket.respond_to?(:connect_nonblock))
check("Socket#ipv6only!", raw_socket.respond_to?(:ipv6only!))
check("Socket#listen", raw_socket.respond_to?(:listen))
check("Socket#recvfrom", raw_socket.respond_to?(:recvfrom))
check("Socket#recvfrom_nonblock", raw_socket.respond_to?(:recvfrom_nonblock))
check("Socket#sysaccept", raw_socket.respond_to?(:sysaccept))

addrinfo = Addrinfo.allocate
check("Addrinfo#afamily", addrinfo.respond_to?(:afamily))
check("Addrinfo#bind", addrinfo.respond_to?(:bind))
check("Addrinfo#canonname", addrinfo.respond_to?(:canonname))
check("Addrinfo#connect", addrinfo.respond_to?(:connect))
check("Addrinfo#connect_from", addrinfo.respond_to?(:connect_from))
check("Addrinfo#connect_internal", addrinfo.respond_to?(:connect_internal, true))
check("Addrinfo#connect_to", addrinfo.respond_to?(:connect_to))
check("Addrinfo#family_addrinfo", addrinfo.respond_to?(:family_addrinfo))
check("Addrinfo#getnameinfo", addrinfo.respond_to?(:getnameinfo))
check("Addrinfo#inspect", addrinfo.respond_to?(:inspect))
check("Addrinfo#inspect_sockaddr", addrinfo.respond_to?(:inspect_sockaddr))
check("Addrinfo#ip?", addrinfo.respond_to?(:ip?))
check("Addrinfo#ip_address", addrinfo.respond_to?(:ip_address))
check("Addrinfo#ip_port", addrinfo.respond_to?(:ip_port))
check("Addrinfo#ip_unpack", addrinfo.respond_to?(:ip_unpack))
check("Addrinfo#ipv4?", addrinfo.respond_to?(:ipv4?))
check("Addrinfo#ipv4_loopback?", addrinfo.respond_to?(:ipv4_loopback?))
check("Addrinfo#ipv4_multicast?", addrinfo.respond_to?(:ipv4_multicast?))
check("Addrinfo#ipv4_private?", addrinfo.respond_to?(:ipv4_private?))
check("Addrinfo#ipv6?", addrinfo.respond_to?(:ipv6?))
check("Addrinfo#ipv6_linklocal?", addrinfo.respond_to?(:ipv6_linklocal?))
check("Addrinfo#ipv6_loopback?", addrinfo.respond_to?(:ipv6_loopback?))
check("Addrinfo#ipv6_mc_global?", addrinfo.respond_to?(:ipv6_mc_global?))
check("Addrinfo#ipv6_mc_linklocal?", addrinfo.respond_to?(:ipv6_mc_linklocal?))
check("Addrinfo#ipv6_mc_nodelocal?", addrinfo.respond_to?(:ipv6_mc_nodelocal?))
check("Addrinfo#ipv6_mc_orglocal?", addrinfo.respond_to?(:ipv6_mc_orglocal?))
check("Addrinfo#ipv6_mc_sitelocal?", addrinfo.respond_to?(:ipv6_mc_sitelocal?))
check("Addrinfo#ipv6_multicast?", addrinfo.respond_to?(:ipv6_multicast?))
check("Addrinfo#ipv6_sitelocal?", addrinfo.respond_to?(:ipv6_sitelocal?))
check("Addrinfo#ipv6_to_ipv4", addrinfo.respond_to?(:ipv6_to_ipv4))
check("Addrinfo#ipv6_unique_local?", addrinfo.respond_to?(:ipv6_unique_local?))
check("Addrinfo#ipv6_unspecified?", addrinfo.respond_to?(:ipv6_unspecified?))
check("Addrinfo#ipv6_v4compat?", addrinfo.respond_to?(:ipv6_v4compat?))
check("Addrinfo#ipv6_v4mapped?", addrinfo.respond_to?(:ipv6_v4mapped?))
check("Addrinfo#listen", addrinfo.respond_to?(:listen))
check("Addrinfo#marshal_dump", addrinfo.respond_to?(:marshal_dump))
check("Addrinfo#marshal_load", addrinfo.respond_to?(:marshal_load))
check("Addrinfo#pfamily", addrinfo.respond_to?(:pfamily))
check("Addrinfo#protocol", addrinfo.respond_to?(:protocol))
check("Addrinfo#socktype", addrinfo.respond_to?(:socktype))
check("Addrinfo#to_s", addrinfo.respond_to?(:to_s))
check("Addrinfo#to_sockaddr", addrinfo.respond_to?(:to_sockaddr))
check("Addrinfo#unix?", addrinfo.respond_to?(:unix?))
check("Addrinfo#unix_path", addrinfo.respond_to?(:unix_path))

option = Socket::Option.allocate
check("Socket::Option#bool", option.respond_to?(:bool))
check("Socket::Option#byte", option.respond_to?(:byte))
check("Socket::Option#data", option.respond_to?(:data))
check("Socket::Option#family", option.respond_to?(:family))
check("Socket::Option#inspect", option.respond_to?(:inspect))
check("Socket::Option#int", option.respond_to?(:int))
check("Socket::Option#ipv4_multicast_loop", option.respond_to?(:ipv4_multicast_loop))
check("Socket::Option#ipv4_multicast_ttl", option.respond_to?(:ipv4_multicast_ttl))
check("Socket::Option#level", option.respond_to?(:level))
check("Socket::Option#linger", option.respond_to?(:linger))
check("Socket::Option#optname", option.respond_to?(:optname))
check("Socket::Option#to_s", option.respond_to?(:to_s))
check("Socket::Option#unpack", option.respond_to?(:unpack))

ancillary = Socket::AncillaryData.allocate
check("Socket::AncillaryData#cmsg_is?", ancillary.respond_to?(:cmsg_is?))
check("Socket::AncillaryData#data", ancillary.respond_to?(:data))
check("Socket::AncillaryData#family", ancillary.respond_to?(:family))
check("Socket::AncillaryData#inspect", ancillary.respond_to?(:inspect))
check("Socket::AncillaryData#int", ancillary.respond_to?(:int))
check("Socket::AncillaryData#ip_pktinfo", ancillary.respond_to?(:ip_pktinfo))
check("Socket::AncillaryData#ipv6_pktinfo", ancillary.respond_to?(:ipv6_pktinfo))
check("Socket::AncillaryData#ipv6_pktinfo_addr", ancillary.respond_to?(:ipv6_pktinfo_addr))
check("Socket::AncillaryData#ipv6_pktinfo_ifindex", ancillary.respond_to?(:ipv6_pktinfo_ifindex))
check("Socket::AncillaryData#level", ancillary.respond_to?(:level))
check("Socket::AncillaryData#timestamp", ancillary.respond_to?(:timestamp))
check("Socket::AncillaryData#type", ancillary.respond_to?(:type))
check("Socket::AncillaryData#unix_rights", ancillary.respond_to?(:unix_rights))
